#!/usr/bin/env bash
#
# sphinx-make-latexpdf-with-BXcoloremoji.sh
# Copyright 2022 (c) Koichi OKADA. All rights reserved.
# This script is distributed under the MIT license.
#

if ! grep -q "Configuration file for the Sphinx documentation builder." conf.py; then
  echo -e "Error: This directory is not for sphinx."
  exit 1
fi

SCRIPT_PATH="$0"
SCRIPT_FILE="${SCRIPT_PATH##*/}"
SCRIPT_NAME="${SCRIPT_FILE%.*}"
SCRIPT_DIR="${SCRIPT_PATH%/*}"
SCRIPT_REALPATH="$(readlink -f "$SCRIPT_PATH")"
SCRIPT_REALFILE="${SCRIPT_REALPATH##*/}"
SCRIPT_REALNAME="${SCRIPT_REALFILE%.*}"
SCRIPT_REALDIR="${SCRIPT_REALPATH%/*}"

mkdir -p _build/latex BXcoloremoji-master

# Prepare BXcoloremoji package
if [ ! -e BXcoloremoji-master/master.tar.gz ]; then
  (
    cd BXcoloremoji-master
    wget https://github.com/zr-tex8r/BXcoloremoji/archive/refs/heads/master.tar.gz
  )
  tar xf BXcoloremoji-master/master.tar.gz
fi
[ ! -e _build/latex/emoji_images           ] && ln -s ../../BXcoloremoji-master/emoji_images           _build/latex/
[ ! -e _build/latex/bxcoloremoji.sty       ] && ln -s ../../BXcoloremoji-master/bxcoloremoji.sty       _build/latex/
[ ! -e _build/latex/bxcoloremoji-names.def ] && ln -s ../../BXcoloremoji-master/bxcoloremoji-names.def _build/latex/

# Make PDF file from latex which generated by sphinx
make latex
(
  cd _build/latex
  for i in *.tex; do
    [ "$i.orig" -a "$i.orig" -ot "$i" ] || continue
    mv -v "$i" "$i.orig"
    "$SCRIPT_REALDIR/BXcoloremojinize.rb" "$i.orig" > "$i"
    touch -r "$i.orig" "$i"
  done
  make
)
